"""Embedding-provider abstraction with an OpenAI-compatible implementation."""

from __future__ import annotations

from typing import Protocol

from openai import OpenAI

from app.core.config import Settings, get_settings


class EmbeddingProvider(Protocol):
    """Contract implemented by any text embedding provider."""

    def embed_texts(self, texts: list[str]) -> list[list[float]]:
        """Return one embedding vector for every supplied text."""


class EmbeddingProviderError(RuntimeError):
    """Raised when embeddings cannot be generated by the configured provider."""


class OpenAICompatibleEmbeddingProvider:
    """Embedding provider for OpenAI and OpenAI-compatible APIs."""

    def __init__(self, settings: Settings) -> None:
        if not settings.openai_api_key:
            raise EmbeddingProviderError("OPENAI_API_KEY is required to generate embeddings")
        client_options: dict[str, str] = {"api_key": settings.openai_api_key}
        if settings.openai_base_url:
            client_options["base_url"] = settings.openai_base_url
        self._client = OpenAI(**client_options)
        self._model = settings.embedding_model
        self._batch_size = settings.embedding_batch_size

    def embed_texts(self, texts: list[str]) -> list[list[float]]:
        """Generate embeddings in bounded batches while retaining input order."""
        if not texts:
            return []
        vectors: list[list[float]] = []
        try:
            for start in range(0, len(texts), self._batch_size):
                response = self._client.embeddings.create(
                    model=self._model, input=texts[start : start + self._batch_size]
                )
                vectors.extend(item.embedding for item in response.data)
        except Exception as error:
            raise EmbeddingProviderError("Embedding provider request failed") from error
        if len(vectors) != len(texts):
            raise EmbeddingProviderError("Embedding provider returned an unexpected vector count")
        return vectors


class MockEmbeddingProvider:
    """In-memory embedding provider for local development and tests."""

    def embed_texts(self, texts: list[str]) -> list[list[float]]:
        return [[0.0, 0.0, 0.0] for _ in texts]


def create_embedding_provider(settings: Settings) -> EmbeddingProvider:
    """Return the configured embedding provider for the given settings."""
    if settings.embedding_provider == "openai":
        return OpenAICompatibleEmbeddingProvider(settings)
    if settings.embedding_provider == "mock":
        return MockEmbeddingProvider()
    raise EmbeddingProviderError(f"Unsupported embedding provider: {settings.embedding_provider}")


def get_embedding_provider() -> EmbeddingProvider:
    """Build the configured provider at the application boundary."""
    return create_embedding_provider(get_settings())
